### ISSUE TITLE
NoSuchMethodError MultivaluedMap.addAll

### ISSUE THREAD

**Issue by agustisanchez** [pingidentity/scim#16]
java.lang.NoSuchMethodError: javax.ws.rs.core.MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V
	at org.glassfish.jersey.client.ClientRequest.accept(ClientRequest.java:326)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.accept(JerseyInvocation.java:237)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.accept(JerseyInvocation.java:154)
	at com.unboundid.scim.facade.org.apache.wink.client.Resource.get(Resource.java:177)
	at com.unboundid.scim.sdk.SCIMEndpoint.query(SCIMEndpoint.java:353)
	at com.unboundid.scim.sdk.SCIMEndpoint.query(SCIMEndpoint.java:276)
	at com.unboundid.scim.sdk.SCIMEndpoint.query(SCIMEndpoint.java:254)

This is because Apache Wink 1.4 adds an incompatible JAX-RS 1.1 library, you must exclude it in the project's POM file:
```xml
		<dependency>
			<groupId>com.unboundid.product.scim</groupId>
			<artifactId>scim-sdk</artifactId>
			<version>1.8.20</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.geronimo.specs</groupId>
					<artifactId>geronimo-jaxrs_1.1_spec</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
xml

**Comment by kenneth-ping** [comment]
This project has been archived and will no longer be maintained.  Please migrate your apps to SCIM v2.
